url: https://ajpy08.github.io
# baseurl: /

# Site settings
title: ISC Angel Javier Puc Yamá
email: angelpuc08@gmail.com
description: "'Ingeniero que tiene ceros y unos en las venas' Soy amante de las nuevas tecnologías, siempre me gusta ir creciendo profesionalmente en las nuevas tecnologías de la actualidad, me gusta experimentar, aprender, compartir conocimiento y crear código. Me gusta el diseño, la creatividad, la mejora continua y todo lo relacionado con Android. Me considero una persona puntual y proactiva, de rápido aprendizaje y confiable."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Angel Javier Puc Yamá
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: "https://twitter.com/ajpy08"
    - title: facebook
      url: "https://facebook.com/angelpucyama"
    - title: github
      url: "https://github.com/ajpy08"
    - title: envelope
      url: mailto:angelpuc08@gmail.com

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: "http://twitter.com/ajpy08"
  - title: facebook
    url: "https://facebook.com/iscangelpy"
  - title: google-plus
    url: "https://plus.google.com/+AngelPuc"
  # - title: bitbucket 
  #   url: #
  - title: github
    url: "https://github.com/ajpy08"
  - title: envelope
    url: mailto:angelpuc08@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Serapio Rendon III
  - line: Mérida Yucatán México, CP 97285

# Build settings
markdown: kramdown
permalink: pretty